import type { EventType } from '@/types/events'

export interface EventTheme {
  type: EventType
  label: string
  emoji: string
  icon: string
  gradient: string
  bgTint: string
  bgTintDark: string
  ring: string
  calendarChip: string
  calendarChipDark: string
  primaryColor: string
  animation: 'confetti' | 'fadeSlide' | 'float' | 'slideUp' | 'pulse' | 'wave' | 'glitch' | 'breathe' | 'splash' | 'sparkle' | 'glow'
  formDecoration: string
  suggestions: string[]
}

export const EVENT_THEMES: Record<EventType, EventTheme> = {
  party: {
    type: 'party',
    label: 'Party / Social',
    emoji: '🎉',
    icon: 'PartyPopper',
    gradient: 'from-rose-500 to-orange-400',
    bgTint: 'bg-rose-50',
    bgTintDark: 'dark:bg-rose-950/20',
    ring: 'ring-rose-500/30',
    calendarChip: 'bg-rose-100 text-rose-700 border-rose-200',
    calendarChipDark: 'dark:bg-rose-900/30 dark:text-rose-300 dark:border-rose-800',
    primaryColor: '#F43F5E',
    animation: 'confetti',
    formDecoration: 'Confetti particles, floating party emojis',
    suggestions: ['Party outfit ideas', 'Gift suggestions', 'Plus-one etiquette'],
  },
  educational: {
    type: 'educational',
    label: 'Educational',
    emoji: '📚',
    icon: 'GraduationCap',
    gradient: 'from-blue-500 to-cyan-400',
    bgTint: 'bg-blue-50',
    bgTintDark: 'dark:bg-blue-950/20',
    ring: 'ring-blue-500/30',
    calendarChip: 'bg-blue-100 text-blue-700 border-blue-200',
    calendarChipDark: 'dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800',
    primaryColor: '#3B82F6',
    animation: 'fadeSlide',
    formDecoration: 'Book stack icon, pencil line animation',
    suggestions: ['Notebook & pen', 'Reading materials', 'Questions to ask'],
  },
  trip: {
    type: 'trip',
    label: 'Trip / Travel',
    emoji: '✈️',
    icon: 'Plane',
    gradient: 'from-teal-500 to-sky-400',
    bgTint: 'bg-teal-50',
    bgTintDark: 'dark:bg-teal-950/20',
    ring: 'ring-teal-500/30',
    calendarChip: 'bg-teal-100 text-teal-700 border-teal-200',
    calendarChipDark: 'dark:bg-teal-900/30 dark:text-teal-300 dark:border-teal-800',
    primaryColor: '#14B8A6',
    animation: 'float',
    formDecoration: 'Floating clouds, plane icon, destination pin',
    suggestions: ['Packing list', 'Weather at destination', 'Travel time estimate', 'Nearby restaurants & attractions'],
  },
  business: {
    type: 'business',
    label: 'Business / Meeting',
    emoji: '💼',
    icon: 'Briefcase',
    gradient: 'from-slate-600 to-gray-500',
    bgTint: 'bg-slate-50',
    bgTintDark: 'dark:bg-slate-950/20',
    ring: 'ring-slate-500/30',
    calendarChip: 'bg-slate-100 text-slate-700 border-slate-200',
    calendarChipDark: 'dark:bg-slate-800/50 dark:text-slate-300 dark:border-slate-700',
    primaryColor: '#64748B',
    animation: 'slideUp',
    formDecoration: 'Minimal, clean lines, subtle grid pattern',
    suggestions: ['Dress code', 'Agenda preparation', 'Meeting notes template', 'Follow-up action items'],
  },
  sports: {
    type: 'sports',
    label: 'Sports / Fitness',
    emoji: '🏋️',
    icon: 'Dumbbell',
    gradient: 'from-green-500 to-emerald-400',
    bgTint: 'bg-green-50',
    bgTintDark: 'dark:bg-green-950/20',
    ring: 'ring-green-500/30',
    calendarChip: 'bg-green-100 text-green-700 border-green-200',
    calendarChipDark: 'dark:bg-green-900/30 dark:text-green-300 dark:border-green-800',
    primaryColor: '#22C55E',
    animation: 'pulse',
    formDecoration: 'Energy pulse rings, heartbeat line',
    suggestions: ['Athletic wear', 'Hydration plan', 'Warm-up routine', 'Equipment check'],
  },
  concert: {
    type: 'concert',
    label: 'Concert / Music',
    emoji: '🎵',
    icon: 'Music',
    gradient: 'from-purple-500 to-violet-400',
    bgTint: 'bg-purple-50',
    bgTintDark: 'dark:bg-purple-950/20',
    ring: 'ring-purple-500/30',
    calendarChip: 'bg-purple-100 text-purple-700 border-purple-200',
    calendarChipDark: 'dark:bg-purple-900/30 dark:text-purple-300 dark:border-purple-800',
    primaryColor: '#A855F7',
    animation: 'wave',
    formDecoration: 'Audio waveform line, floating music notes',
    suggestions: ['Concert outfit', 'Ear protection', 'Venue info & map', 'Parking/transit options'],
  },
  dining: {
    type: 'dining',
    label: 'Dining',
    emoji: '🍽️',
    icon: 'UtensilsCrossed',
    gradient: 'from-amber-500 to-orange-400',
    bgTint: 'bg-amber-50',
    bgTintDark: 'dark:bg-amber-950/20',
    ring: 'ring-amber-500/30',
    calendarChip: 'bg-amber-100 text-amber-700 border-amber-200',
    calendarChipDark: 'dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
    primaryColor: '#F59E0B',
    animation: 'fadeSlide',
    formDecoration: 'Plate icon, subtle cutlery pattern',
    suggestions: ['Dress code', 'Dietary restrictions to share', 'Reservation confirmation', 'Menu preview'],
  },
  birthday: {
    type: 'birthday',
    label: 'Birthday / Celebration',
    emoji: '🎂',
    icon: 'Cake',
    gradient: 'from-pink-500 to-rose-400',
    bgTint: 'bg-pink-50',
    bgTintDark: 'dark:bg-pink-950/20',
    ring: 'ring-pink-500/30',
    calendarChip: 'bg-pink-100 text-pink-700 border-pink-200',
    calendarChipDark: 'dark:bg-pink-900/30 dark:text-pink-300 dark:border-pink-800',
    primaryColor: '#EC4899',
    animation: 'confetti',
    formDecoration: 'Floating balloons, cake candles, confetti',
    suggestions: ['Gift ideas', 'Birthday card message', 'Party supplies checklist', 'Cake or dessert'],
  },
  tech: {
    type: 'tech',
    label: 'Tech / Hackathon',
    emoji: '💻',
    icon: 'Code2',
    gradient: 'from-emerald-400 to-green-500',
    bgTint: 'bg-gray-50',
    bgTintDark: 'dark:bg-gray-950',
    ring: 'ring-green-500/30',
    calendarChip: 'bg-gray-100 text-green-700 border-gray-200',
    calendarChipDark: 'dark:bg-gray-800 dark:text-green-400 dark:border-gray-700',
    primaryColor: '#10B981',
    animation: 'glitch',
    formDecoration: 'Terminal cursor blink, code rain background',
    suggestions: ['Laptop & charger', 'Dev environment ready', 'API keys & credentials', 'Project repositories'],
  },
  health: {
    type: 'health',
    label: 'Health / Medical',
    emoji: '🏥',
    icon: 'HeartPulse',
    gradient: 'from-emerald-400 to-teal-400',
    bgTint: 'bg-emerald-50',
    bgTintDark: 'dark:bg-emerald-950/20',
    ring: 'ring-emerald-500/30',
    calendarChip: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    calendarChipDark: 'dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800',
    primaryColor: '#10B981',
    animation: 'breathe',
    formDecoration: 'Heartbeat line, calm gradient pulse',
    suggestions: ['Insurance card', 'Medical records', 'Fasting requirements', 'Questions for doctor'],
  },
  art: {
    type: 'art',
    label: 'Art / Creative',
    emoji: '🎨',
    icon: 'Palette',
    gradient: 'from-fuchsia-500 to-pink-400',
    bgTint: 'bg-fuchsia-50',
    bgTintDark: 'dark:bg-fuchsia-950/20',
    ring: 'ring-fuchsia-500/30',
    calendarChip: 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200',
    calendarChipDark: 'dark:bg-fuchsia-900/30 dark:text-fuchsia-300 dark:border-fuchsia-800',
    primaryColor: '#D946EF',
    animation: 'splash',
    formDecoration: 'Paint splatter accents, color wheel hint',
    suggestions: ['Art supplies to bring', 'Inspiration references', 'Comfortable clothing'],
  },
  wedding: {
    type: 'wedding',
    label: 'Wedding',
    emoji: '💒',
    icon: 'Heart',
    gradient: 'from-rose-300 to-pink-300',
    bgTint: 'bg-rose-50',
    bgTintDark: 'dark:bg-rose-950/10',
    ring: 'ring-rose-400/30',
    calendarChip: 'bg-rose-100 text-rose-600 border-rose-200',
    calendarChipDark: 'dark:bg-rose-900/20 dark:text-rose-300 dark:border-rose-800',
    primaryColor: '#FB7185',
    animation: 'sparkle',
    formDecoration: 'Floating hearts, elegant gold accents, rings icon',
    suggestions: ['Dress code', 'Gift registry link', 'RSVP deadline', 'Speech preparation', 'Transportation plan'],
  },
  volunteer: {
    type: 'volunteer',
    label: 'Volunteer / Community',
    emoji: '🤝',
    icon: 'HandHeart',
    gradient: 'from-amber-400 to-yellow-400',
    bgTint: 'bg-amber-50',
    bgTintDark: 'dark:bg-amber-950/20',
    ring: 'ring-amber-400/30',
    calendarChip: 'bg-amber-100 text-amber-700 border-amber-200',
    calendarChipDark: 'dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
    primaryColor: '#FBBF24',
    animation: 'glow',
    formDecoration: 'Warm glow, helping hands icon',
    suggestions: ['What to wear', 'What to bring', 'Waiver/forms', 'Carpool options'],
  },
  general: {
    type: 'general',
    label: 'General',
    emoji: '📅',
    icon: 'CalendarDays',
    gradient: 'from-indigo-500 to-blue-400',
    bgTint: 'bg-indigo-50',
    bgTintDark: 'dark:bg-indigo-950/20',
    ring: 'ring-indigo-500/30',
    calendarChip: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    calendarChipDark: 'dark:bg-indigo-900/30 dark:text-indigo-300 dark:border-indigo-800',
    primaryColor: '#6366F1',
    animation: 'fadeSlide',
    formDecoration: 'Clean, subtle calendar grid pattern',
    suggestions: [],
  },
}

/**
 * Get the theme for a given event type.
 */
export function getEventTheme(type: EventType): EventTheme {
  return EVENT_THEMES[type] || EVENT_THEMES.general
}

/**
 * Get all event types as options for select dropdowns.
 */
export function getEventTypeOptions() {
  return Object.values(EVENT_THEMES).map(theme => ({
    value: theme.type,
    label: `${theme.emoji} ${theme.label}`,
    emoji: theme.emoji,
    color: theme.primaryColor,
  }))
}
